/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  CurveBabyJubJub,
  CurveBabyJubJubInterface,
} from "../../../../contracts/crypto/BabyJubJub.sol/CurveBabyJubJub";

const _abi = [
  {
    inputs: [],
    name: "A",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "D",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "Q",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60cc610039600b82828239805160001a60731461002c57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060475760003560e01c80630f529ba214604c578063e493ef8c146067578063f446c1d014608d575b600080fd5b6055620292f881565b60405190815260200160405180910390f35b60557f30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f000000181565b6055620292fc8156fea26469706673582212204ccdf207d7fb8aae388605ddee05708cfd40ea5b84cd4c7e9802089515e8f2e564736f6c63430008140033";

type CurveBabyJubJubConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CurveBabyJubJubConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CurveBabyJubJub__factory extends ContractFactory {
  constructor(...args: CurveBabyJubJubConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      CurveBabyJubJub & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): CurveBabyJubJub__factory {
    return super.connect(runner) as CurveBabyJubJub__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CurveBabyJubJubInterface {
    return new Interface(_abi) as CurveBabyJubJubInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): CurveBabyJubJub {
    return new Contract(address, _abi, runner) as unknown as CurveBabyJubJub;
  }
}
