/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockEAS } from "./MockEAS";
export type { MockERC20 } from "./MockERC20";
export type { MockGitcoinPassportDecoder } from "./MockGitcoinPassportDecoder";
export type { MockHatsProtocol } from "./MockHatsProtocol";
export type { MockSemaphore } from "./MockSemaphore";
export type { MockTally } from "./MockTally";
