/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGitcoinPassportDecoder,
  IGitcoinPassportDecoderInterface,
} from "../../../contracts/interfaces/IGitcoinPassportDecoder";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getPassport",
    outputs: [
      {
        components: [
          {
            internalType: "string",
            name: "provider",
            type: "string",
          },
          {
            internalType: "bytes32",
            name: "hash",
            type: "bytes32",
          },
          {
            internalType: "uint64",
            name: "time",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "expirationTime",
            type: "uint64",
          },
        ],
        internalType: "struct Credential[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getScore",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "isHuman",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IGitcoinPassportDecoder__factory {
  static readonly abi = _abi;
  static createInterface(): IGitcoinPassportDecoderInterface {
    return new Interface(_abi) as IGitcoinPassportDecoderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGitcoinPassportDecoder {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IGitcoinPassportDecoder;
  }
}
