/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMACI,
  IMACIInterface,
} from "../../../contracts/interfaces/IMACI";

const _abi = [
  {
    inputs: [],
    name: "getStateTreeRoot",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "numSignUps",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "stateTreeDepth",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMACI__factory {
  static readonly abi = _abi;
  static createInterface(): IMACIInterface {
    return new Interface(_abi) as IMACIInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IMACI {
    return new Contract(address, _abi, runner) as unknown as IMACI;
  }
}
