/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISemaphore,
  ISemaphoreInterface,
} from "../../../contracts/interfaces/ISemaphore";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "groupId",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "merkleTreeDepth",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "merkleTreeRoot",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "nullifier",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "message",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "scope",
            type: "uint256",
          },
          {
            internalType: "uint256[8]",
            name: "points",
            type: "uint256[8]",
          },
        ],
        internalType: "struct ISemaphore.SemaphoreProof",
        name: "proof",
        type: "tuple",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISemaphore__factory {
  static readonly abi = _abi;
  static createInterface(): ISemaphoreInterface {
    return new Interface(_abi) as ISemaphoreInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ISemaphore {
    return new Contract(address, _abi, runner) as unknown as ISemaphore;
  }
}
