/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { PayableOverrides } from "../../../common";
import type {
  FreeForAllGatekeeper,
  FreeForAllGatekeeperInterface,
} from "../../../contracts/gatekeepers/FreeForAllGatekeeper";

const _abi = [
  {
    inputs: [],
    stateMutability: "payable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "getTrait",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "register",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_maci",
        type: "address",
      },
    ],
    name: "setMaciInstance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405261023a806100136000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806313e65cf31461004657806324b8fbf614610059578063cea9a2631461006b575b600080fd5b6100576100543660046100bc565b50565b005b6100576100673660046100f4565b5050565b604080518082018252600a815269119c9959519bdc905b1b60b21b6020820152905161009791906101b6565b60405180910390f35b80356001600160a01b03811681146100b757600080fd5b919050565b6000602082840312156100ce57600080fd5b6100d7826100a0565b9392505050565b634e487b7160e01b600052604160045260246000fd5b6000806040838503121561010757600080fd5b610110836100a0565b9150602083013567ffffffffffffffff8082111561012d57600080fd5b818501915085601f83011261014157600080fd5b813581811115610153576101536100de565b604051601f8201601f19908116603f0116810190838211818310171561017b5761017b6100de565b8160405282815288602084870101111561019457600080fd5b8260208601602083013760006020848301015280955050505050509250929050565b600060208083528351808285015260005b818110156101e3578581018301518582016040015282016101c7565b506000604082860101526040601f19601f830116850101925050509291505056fea26469706673582212209bd1c5e869bfc84e59a119a4ed6f7d56698f61392e93e094e56c724cfe64ae1d64736f6c63430008140033";

type FreeForAllGatekeeperConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: FreeForAllGatekeeperConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class FreeForAllGatekeeper__factory extends ContractFactory {
  constructor(...args: FreeForAllGatekeeperConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: PayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      FreeForAllGatekeeper & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): FreeForAllGatekeeper__factory {
    return super.connect(runner) as FreeForAllGatekeeper__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FreeForAllGatekeeperInterface {
    return new Interface(_abi) as FreeForAllGatekeeperInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): FreeForAllGatekeeper {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as FreeForAllGatekeeper;
  }
}
