/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BigNumberish,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockSemaphore,
  MockSemaphoreInterface,
} from "../../../contracts/mocks/MockSemaphore";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_groupId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "flipValid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "groupId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "valid",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_groupId",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "merkleTreeDepth",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "merkleTreeRoot",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "nullifier",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "message",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "scope",
            type: "uint256",
          },
          {
            internalType: "uint256[8]",
            name: "points",
            type: "uint256[8]",
          },
        ],
        internalType: "struct ISemaphore.SemaphoreProof",
        name: "proof",
        type: "tuple",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60a06040526000805460ff1916600117905534801561001d57600080fd5b506040516101c13803806101c183398101604081905261003c91610044565b60805261005d565b60006020828403121561005657600080fd5b5051919050565b60805161014a6100776000396000609d015261014a6000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80633d45d9ea14610051578063456f41881461006a578063a0f44c9214610098578063c1991219146100cd575b600080fd5b6100686000805460ff19811660ff90911615179055565b005b6100836100783660046100da565b505060005460ff1690565b60405190151581526020015b60405180910390f35b6100bf7f000000000000000000000000000000000000000000000000000000000000000081565b60405190815260200161008f565b6000546100839060ff1681565b6000808284036101c08112156100ef57600080fd5b833592506101a0601f198201121561010657600080fd5b50602083019050925092905056fea2646970667358221220d74eeacf0d0b762af1910473683ec48c6be10535375463cb1467a50889e1144764736f6c63430008140033";

type MockSemaphoreConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockSemaphoreConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockSemaphore__factory extends ContractFactory {
  constructor(...args: MockSemaphoreConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _groupId: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_groupId, overrides || {});
  }
  override deploy(
    _groupId: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_groupId, overrides || {}) as Promise<
      MockSemaphore & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockSemaphore__factory {
    return super.connect(runner) as MockSemaphore__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockSemaphoreInterface {
    return new Interface(_abi) as MockSemaphoreInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockSemaphore {
    return new Contract(address, _abi, runner) as unknown as MockSemaphore;
  }
}
