/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockTally,
  MockTallyInterface,
} from "../../../contracts/mocks/MockTally";

const _abi = [
  {
    inputs: [],
    name: "flipReturnValue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "returnValue",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_voteOptionIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_spent",
        type: "uint256",
      },
      {
        internalType: "uint256[][]",
        name: "_spentProof",
        type: "uint256[][]",
      },
      {
        internalType: "uint256",
        name: "_spentSalt",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "_voteOptionTreeDepth",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "_spentVoiceCreditsHash",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_resultCommitment",
        type: "uint256",
      },
    ],
    name: "verifyPerVOSpentVoiceCredits",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_totalSpent",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_totalSpentSalt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_resultCommitment",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_perVOSpentVoiceCreditsHash",
        type: "uint256",
      },
    ],
    name: "verifySpentVoiceCredits",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60806040526000805460ff1916600117905534801561001d57600080fd5b506101fb8061002d6000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c806310bc5f51146100515780632d966bf41461008157806358dd748f146100a1578063990c8f79146100ba575b600080fd5b61006d61005f3660046100c7565b60005460ff16949350505050565b604051901515815260200160405180910390f35b61006d61008f36600461010f565b60005460ff1698975050505050505050565b6100b86000805460ff19811660ff90911615179055565b005b60005461006d9060ff1681565b600080600080608085870312156100dd57600080fd5b5050823594602084013594506040840135936060013592509050565b803560ff8116811461010a57600080fd5b919050565b60008060008060008060008060e0898b03121561012b57600080fd5b8835975060208901359650604089013567ffffffffffffffff8082111561015157600080fd5b818b0191508b601f83011261016557600080fd5b81358181111561017457600080fd5b8c60208260051b850101111561018957600080fd5b602083019850809750505050606089013593506101a860808a016100f9565b925060a0890135915060c08901359050929598509295989093965056fea2646970667358221220630f1dc69521128577fd29d32afb90c25c782840d174896ee72250d8222e578d64736f6c63430008140033";

type MockTallyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockTallyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockTally__factory extends ContractFactory {
  constructor(...args: MockTallyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockTally & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockTally__factory {
    return super.connect(runner) as MockTally__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockTallyInterface {
    return new Interface(_abi) as MockTallyInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MockTally {
    return new Contract(address, _abi, runner) as unknown as MockTally;
  }
}
