/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BigNumberish,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { PayableOverrides } from "../../../common";
import type {
  ConstantInitialVoiceCreditProxy,
  ConstantInitialVoiceCreditProxyInterface,
} from "../../../contracts/initialVoiceCreditProxy/ConstantInitialVoiceCreditProxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_balance",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "getVoiceCredits",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60a06040526040516101f03803806101f08339810160408190526100229161002a565b608052610043565b60006020828403121561003c57600080fd5b5051919050565b60805161019361005d6000396000604001526101936000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063b36543a914610030575b600080fd5b61006561003e36600461008d565b7f000000000000000000000000000000000000000000000000000000000000000092915050565b60405190815260200160405180910390f35b634e487b7160e01b600052604160045260246000fd5b600080604083850312156100a057600080fd5b82356001600160a01b03811681146100b757600080fd5b9150602083013567ffffffffffffffff808211156100d457600080fd5b818501915085601f8301126100e857600080fd5b8135818111156100fa576100fa610077565b604051601f8201601f19908116603f0116810190838211818310171561012257610122610077565b8160405282815288602084870101111561013b57600080fd5b826020860160208301376000602084830101528095505050505050925092905056fea264697066735822122095d5cb0ca81edc480cd2a686afb853eda440eab7cbd96dea87a18becec18e1c564736f6c63430008140033";

type ConstantInitialVoiceCreditProxyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ConstantInitialVoiceCreditProxyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ConstantInitialVoiceCreditProxy__factory extends ContractFactory {
  constructor(...args: ConstantInitialVoiceCreditProxyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _balance: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_balance, overrides || {});
  }
  override deploy(
    _balance: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ) {
    return super.deploy(_balance, overrides || {}) as Promise<
      ConstantInitialVoiceCreditProxy & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): ConstantInitialVoiceCreditProxy__factory {
    return super.connect(runner) as ConstantInitialVoiceCreditProxy__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ConstantInitialVoiceCreditProxyInterface {
    return new Interface(_abi) as ConstantInitialVoiceCreditProxyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ConstantInitialVoiceCreditProxy {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ConstantInitialVoiceCreditProxy;
  }
}
